spring.application.name=demo

# Database Connection
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mail Server Configuration
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}

# Protocol and Security
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Application Specifics
app.api.fromAddress=${APP_NOTIFICATION_FROM_ADDRESS}
app.api.frontendAuth=${FRONTEND_AUTH}
app.api.jwtSecret=${JWT_SECRET}

# IBM MQ Connection Settings
ibm.mq.queueManager=${MQ_MNGR}
ibm.mq.channel=${MQ_CHANNEL}
ibm.mq.connName=${MQ_CONNECTION}
ibm.mq.user=${MQ_USER}
ibm.mq.password=${MQ_PASSWORD}

# IBM MQ DLQ Settings

spring.jms.listener.max-concurrency=1
# Force Spring to use the broker's transaction to increment BackoutCount
spring.jms.listener.session-transacted=true
# CRITICAL: Tell Spring NOT to handle retries itself. 
# We want the message to go back to the MQ server every single time it fails.
spring.jms.cache.enabled=false

# ibm.mq.additional-properties.RETRY_COUNT=3
# ibm.mq.additional-properties.RETRY_INTERVAL=5000